name: MD_lab
channels:
 - defaults
 - conda-forge
 - ambermd
 - omnia
dependencies:
 - python=3
 - matplotlib
 - numpy
 - mdtraj
 - nglview
 - scipy
 - pandas
 - brewer2mpl
 - notebook
 - vim
 - jupyter
 - eigen
 - parmed
 - openmp
 - gfortran_linux-64
 - gcc_linux-64
